### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Hu-JIN** [hms-dbmi/higlass-manage#5]
Not sure if this is related issue #4 , but after installing `higlass-manage` on a python3 environment, I tried `higlass-manage start`, and it gave the following error message. 

> /anaconda2/envs/python36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/anaconda2/envs/python36/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/anaconda2/envs/python36/bin/higlass-manage", line 11, in <module>
    sys.exit(cli())
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/higlass_manage.py", line 296, in start
    container = client.containers.get(container_name)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/docker/models/containers.py", line 843, in get
    resp = self.client.api.inspect_container(container_id)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/docker/api/container.py", line 730, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/docker/api/client.py", line 198, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/anaconda2/envs/python36/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Not sure if this will be fixed in v0.1.14. I installed v0.1.13 through `pip`. I also tried some earlier versions, and they all gave the same error message. What might be the problem here? Is it related to that I am installing in a python3 environment? Thanks.

**Comment by pkerpedjiev** [comment]
Just to make sure, do you have Docker installed?

**Comment by Hu-JIN** [comment]
Yes, I do have Docker installed.

**Comment by Hu-JIN** [comment]
I found the reason. After I installed Docker, I never opened it or logged in... Now that I logged in on Docker, the error message went away. Thanks!

**Comment by pkerpedjiev** [comment]
Thanks for reporting, I added a more meaningful error message that will appear in the next release.
