### ISSUE TITLE
Possible issues with options in v0.2.0?

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/higlass-manage#6]
I am running into some problems with running v0.2.0 of `higlass-manage`.

The installation seemed to go okay:

```
# pip uninstall higlass-manage
...
# pip install higlass-manage
...
Successfully built higlass-manage
Installing collected packages: higlass-manage
Successfully installed higlass-manage-0.2.0
```

Once I try to start a server, though, I get an unexpected error:

```
# higlass-manage start --port 80 --site-url hg-dev-rev2.altius.org
Usage: higlass-manage [OPTIONS] COMMAND [ARGS]...

Error: No such command "start".
```

The `start` option seems to have changed to `_start`:

```
# higlass-manage
Usage: higlass-manage [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  _start
  browse           Launch a web browser for a running instance
  createsuperuser  Create a superuser in the container...
  deletesuperuser  Delete a superuser in the container...
  ingest           Ingest a dataset
  list             List running instances
  list_data        List the datasets in an instance
  log              Return the error log for this container
  shell            Start a shell in a higlass container
  stop             Stop a running instance
  view             View a file in higlass.
```

Also, if I use this option, the other options do not seem to be processed. For instance, if I specify a `site-url` parameter:

```
# higlass-manage _start --port 80 --site-url example.com
Traceback (most recent call last):
  File "/root/miniconda3/bin/higlass-manage", line 11, in <module>
    sys.exit(cli())
  File "/root/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: _start() got an unexpected keyword argument 'site_url'
```

I was able to downgrade to v0.1.13, but the v0.1.14 tag was not available through `pip`:

```
# pip install higlass-manage==0.1.14
Collecting higlass-manage==0.1.14
  Could not find a version that satisfies the requirement higlass-manage==0.1.14 (from versions: 0.1.1, 0.1.2, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.2.0)
No matching distribution found for higlass-manage==0.1.14
```

**Comment by pkerpedjiev** [comment]
Wow, sorry about that and thanks for reporting! This was a silly typo I introduced recently. 

Setting up CI and tests to make sure something that blatant doesn't happen again.

It should be fixed in v0.2.1.
